// bootserv.h

#define MODID 107
#define NAMELONG "Bootserver 1.0.4-BETA"
#define NAMESHORT "BOOTSERV"

#define DEFAULT_DEBUG 1
#define BUFLEN 4096


enum {BODY_SKIN, BODY_KIT, BODY_NUMBERS, BODY_SHORTS_NUMBERS, BODY_BOOTS,
	BODY_UNKNOWN1, BODY_NAME, BODY_UNKNOWN2, BODY_DIRT};
